apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-server
  template:
    metadata:
      labels:
        app: weather-server
    spec:
      containers:
      - name: weather-server
        image: snowy_server:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 15000
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  type: NodePort  # Dış dünyadan erişim için değiştirildi
  selector:
    app: weather-server
  ports:
    - protocol: TCP
      port: 15000         # Pod'un dinlediği port
      targetPort: 15000   # Container içinde çalışan port
      nodePort: 30000    # Tarayıcıdan erişmek için dış port (30000-32767 arası olabilir)