apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # Tarayıcıdan erişmek için bu portu kullanacağız
