apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80       # Dış dünyaya açılan port
      targetPort: 5000  # Container içindeki Flask uygulamasının portu
  type: LoadBalancer  # Servisi dış dünyaya açar
