name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'  # Sadece v ile başlayan tag'ler push edildiğinde çalışacak

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      # 1. Adım: Repository'yi checkout et
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Prepare Release Body
        id: prepare_release_body
        run: |
            BODY="## 🚀 Yeni Sürüm: v1.0.1
            ### Değişiklikler
            - Yeni özellikler eklendi.
            - Hata düzeltmeleri yapıldı.
            - Performans iyileştirmeleri yapıldı.

            ### Katkıda Bulunanlar
            - @dtarim
            - @gtarim

            ### Detaylar
            Bu sürüm, projenin stabilitesini artırmak için birçok iyileştirme içerir."

            # TAG_NAME değişkenini içeriğe ekleme
            RELEASE_BODY=$(echo "$BODY" | sed "s/\$TAG_NAME/${{ github.ref_name }}/g")

            # RELEASE_BODY'yi ortam değişkeni olarak ayarlama
            echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
            echo "$RELEASE_BODY" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

      - name: DENEMEEE
        id: deneme
        run: |
          echo "release body ${{env.RELEASE_BODY}}"

      # 3. Adım: GitHub Release oluştur
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # GitHub tarafından otomatik sağlanan tag adı
          name: Release ${{ github.ref_name }}  # Release adı
          body: ${{env.RELEASE_BODY}}  # Şablon dosyasından okunan açıklama
          draft: false  # Release'i draft olarak oluşturma
          prerelease: false  # Release'i ön sürüm (pre-release) olarak işaretleme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub tarafından otomatik sağlanan token
