name: Docker Build and Push

on:
  pull_request:
    branches:
        - master
  push:
    branches:
        - master
    tags:
      - 'v2'  # v1.0.0, v2.0.0 gibi tag'ler için çalıştır

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run Tests
        run: pytest test_app.py  # Test dosyanız burada çalıştırılıyor

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Testler başarılı olmadan bu adım çalışmaz

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Version (if release)
        id: get_version
        run: |
            if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
             VERSION="${GITHUB_REF#refs/tags/}"
            else
             VERSION="${GITHUB_REF#refs/heads/}"
            fi
            echo "VERSION=${VERSION}" >> $GITHUB_ENV


      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/snowy_server:${{ env.VERSION }} .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/snowy_server:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/snowy_server:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/snowy_server:latest
