name: Flask App CI

on:
  push: 
    branches:
      - master
  pull_request: 
    branches:
      - master

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Depoyu klonla
      - name: Checkout repository 
        uses: actions/checkout@v3

      # 2. Python kur ve bagimliliklari yükle
      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      # 3. Testleri çalistir
      - name: Run tests 
        run: pytest
